version: "3.9"
services:
  spendapp:
    build: .
    volumes:
      - .:/workspace
      - ./env/.env:/workspace/env/.env 
    env_file:
      - env/.env.example   # Fallback mit Platzhaltern
      - env/.env           # echte Werte, falls vorhanden
    ports:
      - "8888:8888" # falls wir Jupyter nutzen wollen
    command: >
      bash -c "sleep infinity"
